import { create } from "zustand";

export type CityKey = "chennai" | "bengaluru" | "dubai" | "london" | "new_york";
export type LanguageKey = "en" | "es" | "de" | "ta" | "hi" | "te" | "mr" | "bn";
export type RoutingProfileKey = "bike" | "scooter" | "car" | "foot";

export interface CityProfile {
  key: CityKey;
  name: string;
  latitude: number;
  longitude: number;
  currency: string;
  timezone: string;
}

export const cityProfiles: Record<CityKey, CityProfile> = {
  chennai: { key: "chennai", name: "Chennai, India", latitude: 13.0827, longitude: 80.2707, currency: "₹", timezone: "IST" },
  bengaluru: { key: "bengaluru", name: "Bengaluru, India", latitude: 12.9716, longitude: 77.5946, currency: "₹", timezone: "IST" },
  dubai: { key: "dubai", name: "Dubai, UAE", latitude: 25.2048, longitude: 55.2708, currency: "AED", timezone: "GST" },
  london: { key: "london", name: "London, UK", latitude: 51.5074, longitude: -0.1278, currency: "£", timezone: "BST" },
  new_york: { key: "new_york", name: "New York, USA", latitude: 40.7128, longitude: -74.0060, currency: "$", timezone: "EST" }
};

// I18n translation dictionary
export const translations: Record<LanguageKey, Record<string, string>> = {
  en: {
    overview: "Mission Control Overview",
    live_ops: "Live Operations Grid",
    dispatch: "Dispatch Control Center",
    optimization: "Route Optimization Engine",
    ai_ops: "AI Operations Center",
    analytics: "Operational Analytics",
    settings: "System Configuration",
    online: "ONLINE",
    offline: "OFFLINE",
    total_orders: "Total Orders",
    completed: "Completed",
    in_progress: "In Progress",
    delayed: "Delayed",
    active_riders: "Active Riders",
    sla: "On-Time SLA",
    incidents: "Live Incidents & Anomalies",
    execute_solver: "Execute Solver Plan",
    active_mesh: "Active mesh",
    overview_subtitle: "Realtime fleet orchestration, GIS telemetry, and predictive dispatch loops",
    core_active: "Core: Active",
    live_ops_subtitle: "High-frequency active routes, dropoff geofences, and live GPS signals",
    chennai_core: "Chennai Core Area",
    ai_insight: "AI Operational Insight",
    injecting_telemetry: "Injecting operational telemetry context...",
    refresh_predictor: "Refresh Predictor Context",
    high_freq_timeline: "High-Frequency Event Timeline",
    no_anomalies: "No outstanding anomaly flags.",
    language: "Language",
    rider_app: "Rider App",
    opt_engine_desc: "Combinatorial VRP solver jobs, simulated dispatch costs, and fuel savings analysis",
    no_solver_plan: "No Solver Plan Active",
    solver_plan_desc: "Execute the combinatorial OR-Tools solver above to calculate vehicle capacities, dynamic SLA travel matrices, and workload balance scores.",
    dispatch_desc: "Manual delivery override queue, dispatch matching matrices, and SLA overrides",
    intake_queue: "INTAKE QUEUE",
    active_transit: "ACTIVE TRANSIT QUEUE",
    manual_overrides: "Manual Dispatch Overrides",
    live_ops_desc: "Continuous rider tracking, speed vectors, and route deviation analytics",
    active_fleet: "ACTIVE FLEET TELEMETRY"
  },
  es: {
    overview: "Vista General de Misión",
    live_ops: "Red de Operaciones en Vivo",
    dispatch: "Centro de Despacho",
    optimization: "Motor de Optimización de Rutas",
    ai_ops: "Centro de Operaciones de IA",
    analytics: "Análisis Operativo",
    settings: "Configuración del Sistema",
    online: "EN LÍNEA",
    offline: "FUERA DE LÍNEA",
    total_orders: "Pedidos Totales",
    completed: "Completado",
    in_progress: "En Progreso",
    delayed: "Retrasado",
    active_riders: "Repartidores Activos",
    sla: "SLA a Tiempo",
    incidents: "Incidentes y Anomalías en Vivo",
    execute_solver: "Ejecutar Plan del Solver",
    active_mesh: "Red activa",
    overview_subtitle: "Orquestación de flota en tiempo real, telemetría SIG y bucles predictivos",
    core_active: "Núcleo: Activo",
    live_ops_subtitle: "Rutas activas de alta frecuencia, geocercas y señales GPS en vivo",
    chennai_core: "Área Central de Chennai",
    ai_insight: "Perspectiva Operativa de IA",
    injecting_telemetry: "Inyectando contexto de telemetría...",
    refresh_predictor: "Actualizar Contexto",
    high_freq_timeline: "Cronología de Alta Frecuencia",
    no_anomalies: "Sin banderas de anomalías.",
    language: "Idioma",
    rider_app: "App del Repartidor",
    opt_engine_desc: "Trabajos del solucionador VRP combinatorio, costos de despacho simulados y análisis de ahorro de combustible",
    no_solver_plan: "Ningún plan de solucionador activo",
    solver_plan_desc: "Ejecute el solucionador combinatorio OR-Tools arriba para calcular capacidades.",
    dispatch_desc: "Cola de anulación de entrega manual, matrices de coincidencia y anulaciones de SLA",
    intake_queue: "COLA DE INGRESO",
    active_transit: "COLA DE TRÁNSITO ACTIVO",
    manual_overrides: "Anulaciones de Despacho Manual",
    live_ops_desc: "Seguimiento continuo de repartidores, vectores de velocidad y análisis de desvíos",
    active_fleet: "TELEMETRÍA DE FLOTA ACTIVA"
  },
  de: {
    overview: "Mission Control Übersicht",
    live_ops: "Live-Betriebsraster",
    dispatch: "Dispositionszentrum",
    optimization: "Routenoptimierungs-Engine",
    ai_ops: "KI-Operationszentrum",
    analytics: "Betriebliche Analysen",
    settings: "Systemkonfiguration",
    online: "ONLINE",
    offline: "OFFLINE",
    total_orders: "Bestellungen Gesamt",
    completed: "Abgeschlossen",
    in_progress: "In Bearbeitung",
    delayed: "Verspätet",
    active_riders: "Aktive Fahrer",
    sla: "Pünktlichkeits-SLA",
    incidents: "Live-Vorfälle & Anomalien",
    execute_solver: "Solver-Plan Ausführen",
    active_mesh: "Aktives Raster",
    overview_subtitle: "Echtzeit-Flottenorchestrierung, GIS-Telemetrie und prädiktive Dispatch-Schleifen",
    core_active: "Kern: Aktiv",
    live_ops_subtitle: "Aktive Hochfrequenzrouten, Dropoff-Geofences und Live-GPS-Signale",
    chennai_core: "Chennai Kerngebiet",
    ai_insight: "KI-Operationserkenntnis",
    injecting_telemetry: "Betriebstelemetriekontext wird injiziert...",
    refresh_predictor: "Prädiktorkontext aktualisieren",
    high_freq_timeline: "Hochfrequenz-Ereigniszeitleiste",
    no_anomalies: "Keine ausstehenden Anomalien.",
    language: "Sprache",
    rider_app: "Fahrer-App",
    opt_engine_desc: "Kombinatorische VRP-Solver-Aufträge, simulierte Dispositionskosten und Kraftstoffeinsparungen",
    no_solver_plan: "Kein Solver-Plan Aktiv",
    solver_plan_desc: "Führen Sie den kombinatorischen OR-Tools-Solver oben aus, um Fahrzeugkapazitäten zu berechnen.",
    dispatch_desc: "Manuelle Lieferüberschreibungswarteschlange, Dispositionsmatrizen und SLA-Überschreibungen",
    intake_queue: "EINGANGSWARTESCHLANGE",
    active_transit: "AKTIVE TRANSIT-WARTESCHLANGE",
    manual_overrides: "Manuelle Dispositionsüberschreibungen",
    live_ops_desc: "Kontinuierliche Fahrerverfolgung, Geschwindigkeitsvektoren und Routenabweichungsanalysen",
    active_fleet: "AKTIVE FLOTTENTELEMETRIE"
  },
  ta: {
    overview: "கட்டுப்பாட்டு மையம்",
    live_ops: "நேரடி செயல்பாடுகள்",
    dispatch: "பகிர்வு மையம்",
    optimization: "பயண வழிமுறை உகந்ததாக்கல்",
    ai_ops: "செயற்கை நுண்ணறிவு மையம்",
    analytics: "செயல்பாட்டு பகுப்பாய்வு",
    settings: "அமைப்புகள்",
    online: "செயலில்",
    offline: "செயலற்றது",
    total_orders: "மொத்த ஆர்டர்கள்",
    completed: "முடிவடைந்தவை",
    in_progress: "செயல்பாட்டில்",
    delayed: "தாமதமானவை",
    active_riders: "செயலில் உள்ள ஓட்டுநர்கள்",
    sla: "சரியான நேர SLA",
    incidents: "நேரடி முரண்பாடுகள்",
    execute_solver: "தீர்வை இயக்கு",
    active_mesh: "நேரடி வரைபடம்",
    overview_subtitle: "நிகழ்நேர கடற்படை ஒருங்கிணைப்பு, ஜி.ஐ.எஸ் டெலிமெட்ரி மற்றும் முன்கணிப்பு லூப்கள்",
    core_active: "மையம்: செயலில்",
    live_ops_subtitle: "அதிக அதிர்வெண் செயலில் உள்ள வழிகள் மற்றும் நேரடி ஜி.பி.எஸ் சிக்னல்கள்",
    chennai_core: "சென்னை மையப்பகுதி",
    ai_insight: "செயற்கை நுண்ணறிவு நுண்ணறிவு",
    injecting_telemetry: "டெலிமெட்ரி প্রসঙ্গத்தை உட்செலுத்துகிறது...",
    refresh_predictor: "முன்கணிப்பு சூழலை புதுப்பிக்கவும்",
    high_freq_timeline: "உயர் அதிர்வெண் நிகழ்வு காலவரிசை",
    no_anomalies: "முரண்பாடுகள் எதுவும் இல்லை.",
    language: "மொழி",
    rider_app: "ஓட்டுநர் செயலி",
    opt_engine_desc: "வி.ஆர்.பி தீர்வு வேலைகள், உருவகப்படுத்தப்பட்ட செலவுகள் மற்றும் எரிபொருள் சேமிப்பு",
    no_solver_plan: "தீர்வு திட்டம் இல்லை",
    solver_plan_desc: "வாகன திறன்கள் மற்றும் பணிச்சுமை சமநிலை மதிப்பெண்களை கணக்கிட OR-Tools தீர்வை இயக்கவும்.",
    dispatch_desc: "கைமுறை விநியோக வரிசை, பகிர்வு அளவீடுகள் மற்றும் SLA மேலெழுதல்கள்",
    intake_queue: "உள்நுழைவு வரிசை",
    active_transit: "செயலில் உள்ள போக்குவரத்து",
    manual_overrides: "கைமுறை பகிர்வு மேலெழுதல்கள்",
    live_ops_desc: "தொடர்ச்சியான கண்காணிப்பு, வேக திசையன்கள் மற்றும் வழி முரண்பாடு பகுப்பாய்வு",
    active_fleet: "செயலில் உள்ள கடற்படை"
  },
  hi: {
    overview: "मिशन कंट्रोल अवलोकन",
    live_ops: "लाइव ऑपरेशंस ग्रिड",
    dispatch: "डिस्पैच कंट्रोल सेंटर",
    optimization: "रूट ऑप्टिमाइज़ेशन इंजन",
    ai_ops: "एआई ऑपरेशंस सेंटर",
    analytics: "परिचालन विश्लेषण",
    settings: "सिस्टम कॉन्फ़िगरेशन",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    total_orders: "कुल ऑर्डर",
    completed: "पूर्ण",
    in_progress: "प्रगति पर",
    delayed: "विलंबित",
    active_riders: "सक्रिय राइडर्स",
    sla: "समय पर SLA",
    incidents: "लाइव घटनाएँ और विसंगतियाँ",
    execute_solver: "सॉल्वर योजना निष्पादित करें",
    active_mesh: "सक्रिय मेश",
    overview_subtitle: "रीयल-टाइम फ्लीट ऑर्केस्ट्रेशन, जीआईएस टेलीमेट्री और प्रेडिक्टिव डिस्पैच लूप",
    core_active: "कोर: सक्रिय",
    live_ops_subtitle: "उच्च-आवृत्ति सक्रिय मार्ग, ड्रॉपऑफ़ जियोफेंस और लाइव जीपीएस सिग्नल",
    chennai_core: "चेन्नई कोर क्षेत्र",
    ai_insight: "एआई परिचालन अंतर्दृष्टि",
    injecting_telemetry: "परिचालन टेलीमेट्री संदर्भ इंजेक्ट किया जा रहा है...",
    refresh_predictor: "प्रेडिक्टर संदर्भ रीफ्रेश करें",
    high_freq_timeline: "उच्च-आवृत्ति घटना टाइमलाइन",
    no_anomalies: "कोई बकाया विसंगति झंडे नहीं।",
    language: "भाषा",
    rider_app: "राइडर ऐप",
    opt_engine_desc: "कॉम्बिनेटोरियल वीआरपी सॉल्वर जॉब्स, सिम्युलेटेड डिस्पैच लागत और ईंधन बचत विश्लेषण",
    no_solver_plan: "कोई सॉल्वर योजना सक्रिय नहीं",
    solver_plan_desc: "वाहन क्षमता और कार्यभार संतुलन की गणना करने के लिए OR-Tools सॉल्वर निष्पादित करें।",
    dispatch_desc: "मैनुअल डिलीवरी ओवरराइड कतार और एसएलए ओवरराइड",
    intake_queue: "इंटेक कतार",
    active_transit: "सक्रिय पारगमन कतार",
    manual_overrides: "मैनुअल डिस्पैच ओवरराइड",
    live_ops_desc: "निरंतर राइडर ट्रैकिंग, गति वैक्टर और रूट विचलन विश्लेषण",
    active_fleet: "सक्रिय फ्लीट टेलीमेट्री"
  },
  te: {
    overview: "మిషన్ కంట్రోల్ అవలోకనం",
    live_ops: "ప్రత్యక్ష ఆపరేషన్ల గ్రిడ్",
    dispatch: "డిస్పాచ్ కంట్రోల్ సెంటర్",
    optimization: "రూట్ ఆప్టిమైజేషన్ ఇంజిన్",
    ai_ops: "AI ఆపరేషన్స్ సెంటర్",
    analytics: "ఆపరేషనల్ అనలిటిక్స్",
    settings: "సిస్టమ్ కాన్ఫిగరేషన్",
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    total_orders: "మొత్తం ఆర్డర్లు",
    completed: "పూర్తయింది",
    in_progress: "పురోగతిలో ఉంది",
    delayed: "ఆలస్యమైంది",
    active_riders: "క్రియాశీల రైడర్లు",
    sla: "ఆన్-టైమ్ SLA",
    incidents: "లైవ్ సంఘటనలు మరియు అసాధారణతలు",
    execute_solver: "సాల్వర్ ప్లాన్ అమలు చేయండి",
    active_mesh: "యాక్టివ్ మెష్",
    overview_subtitle: "రియల్-టైమ్ ఫ్లీట్ ఆర్కెస్ట్రేషన్, GIS టెలిమెట్రీ మరియు ప్రిడిక్టివ్ డిస్పాచ్ లూప్స్",
    core_active: "కోర్: యాక్టివ్",
    live_ops_subtitle: "హై-ఫ్రీక్వెన్సీ యాక్టివ్ రూట్‌లు, డ్రాప్‌ఆఫ్ జియోఫెన్స్‌లు మరియు లైవ్ GPS సిగ్నల్స్",
    chennai_core: "చెన్నై కోర్ ఏరియా",
    ai_insight: "AI ఆపరేషనల్ ఇన్‌సైట్",
    injecting_telemetry: "ఆపరేషనల్ టెలిమెట్రీ సందర్భాన్ని ఇంజెక్ట్ చేస్తోంది...",
    refresh_predictor: "ప్రిడిక్టర్ సందర్భాన్ని రిఫ్రెష్ చేయండి",
    high_freq_timeline: "హై-ఫ్రీక్వెన్సీ ఈవెంట్ టైమ్‌లైన్",
    no_anomalies: "బకాయి ఉన్న అసాధారణత ఫ్లాగ్‌లు లేవు.",
    language: "భాష",
    rider_app: "రైడర్ యాప్",
    opt_engine_desc: "కాంబినేటోరియల్ VRP సాల్వర్ జాబ్స్, ఖర్చులు మరియు ఇంధన ఆదా విశ్లేషణ",
    no_solver_plan: "సాల్వర్ ప్లాన్ లేదు",
    solver_plan_desc: "వాహన సామర్థ్యాలను లెక్కించడానికి పైన OR-Tools సాల్వర్‌ను అమలు చేయండి.",
    dispatch_desc: "మాన్యువల్ డెలివరీ ఓవర్‌రైడ్ క్యూ మరియు SLA ఓవర్‌రైడ్‌లు",
    intake_queue: "ఇంటేక్ క్యూ",
    active_transit: "యాక్టివ్ ట్రాన్సిట్ క్యూ",
    manual_overrides: "మాన్యువల్ డిస్పాచ్ ఓవర్‌రైడ్‌లు",
    live_ops_desc: "నిరంతర రైడర్ ట్రాకింగ్, స్పీడ్ వెక్టార్‌లు మరియు విశ్లేషణలు",
    active_fleet: "యాక్టివ్ ఫ్లీట్ టెలిమెట్రీ"
  },
  mr: {
    overview: "मिशन कंट्रोल विहंगावलोकन",
    live_ops: "थेट ऑपरेशन्स ग्रिड",
    dispatch: "डिस्पॅच कंट्रोल सेंटर",
    optimization: "रूट ऑप्टिमायझेशन इंजिन",
    ai_ops: "एआय ऑपरेशन्स सेंटर",
    analytics: "ऑपरेशनल अ‍ॅनालिटिक्स",
    settings: "सिस्टम कॉन्फिगरेशन",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    total_orders: "एकूण ऑर्डर",
    completed: "पूर्ण",
    in_progress: "प्रगतीपथावर",
    delayed: "विलंबित",
    active_riders: "सक्रिय रायडर्स",
    sla: "वेळेवर SLA",
    incidents: "थेट घटना आणि विसंगती",
    execute_solver: "सॉल्वर योजना चालवा",
    active_mesh: "सक्रिय मेश",
    overview_subtitle: "रिअल-टाइम फ्लीट ऑर्केस्ट्रेशन, जीआयएस टेलीमेट्री आणि प्रेडिक्टिव डिस्पॅच लूप",
    core_active: "कोर: सक्रिय",
    live_ops_subtitle: "उच्च-फ्रिक्वेन्सी सक्रिय मार्ग, ड्रॉपऑफ जिओफेन्स आणि थेट जीपीएस सिग्नल",
    chennai_core: "चेन्नई कोर क्षेत्र",
    ai_insight: "एआय ऑपरेशनल इनसाइट",
    injecting_telemetry: "ऑपरेशनल टेलीमेट्री संदर्भ इंजेक्ट करत आहे...",
    refresh_predictor: "प्रेडिक्टर संदर्भ रिफ्रेश करा",
    high_freq_timeline: "हाय-फ्रिक्वेन्सी इव्हेंट टाइमलाइन",
    no_anomalies: "कोणतेही थकीत विसंगती ध्वज नाहीत.",
    language: "भाषा",
    rider_app: "रायडर अ‍ॅप",
    opt_engine_desc: "कॉम्बिनेटोरियल व्हीआरपी सॉल्वर जॉब्स, सिम्युलेटेड डिस्पॅच खर्च आणि इंधन बचत",
    no_solver_plan: "कोणतीही सॉल्वर योजना नाही",
    solver_plan_desc: "वाहन क्षमता मोजण्यासाठी वर OR-Tools सॉल्वर चालवा.",
    dispatch_desc: "मॅन्युअल डिलिव्हरी ओव्हरराइड रांग आणि SLA ओव्हरराइड्स",
    intake_queue: "इंटेक रांग",
    active_transit: "सक्रिय संक्रमण रांग",
    manual_overrides: "मॅन्युअल डिस्पॅच ओव्हरराइड्स",
    live_ops_desc: "सतत रायडर ट्रॅकिंग, वेग आणि मार्ग विचलन विश्लेषण",
    active_fleet: "सक्रिय फ्लीट टेलिमेट्री"
  },
  bn: {
    overview: "মিশন কন্ট্রোল ওভারভিউ",
    live_ops: "লাইভ অপারেশন গ্রিড",
    dispatch: "ডেসপ্যাচ কন্ট্রোল সেন্টার",
    optimization: "রুট অপ্টিমাইজেশান ইঞ্জিন",
    ai_ops: "এআই অপারেশন সেন্টার",
    analytics: "অপারেশনাল অ্যানালিটিক্স",
    settings: "সিস্টেম কনফিগারেশন",
    online: "অনলাইন",
    offline: "অফলাইন",
    total_orders: "মোট অর্ডার",
    completed: "সম্পন্ন",
    in_progress: "চলমান",
    delayed: "বিলম্বিত",
    active_riders: "সক্রিয় রাইডার্স",
    sla: "অন-টাইম এসএলএ",
    incidents: "লাইভ ঘটনা এবং অসঙ্গতি",
    execute_solver: "সলভার প্ল্যান চালান",
    active_mesh: "সক্রিয় মেশ",
    overview_subtitle: "রিয়েল-টাইম ফ্লিট অর্কেস্ট্রেশন, জিআইএস টেলিমেট্রি এবং প্রেডিকটিভ ডেসপ্যাচ লুপস",
    core_active: "কোর: সক্রিয়",
    live_ops_subtitle: "উচ্চ-ফ্রিকোয়েন্সি সক্রিয় রুট, ড্রপঅফ জিওফেন্স এবং লাইভ জিপিএস সংকেত",
    chennai_core: "চেন্নাই কোর এলাকা",
    ai_insight: "এআই অপারেশনাল ইনসাইট",
    injecting_telemetry: "অপারেশনাল টেলিমেট্রি প্রসঙ্গ ইনজেক্ট করা হচ্ছে...",
    refresh_predictor: "প্রেডিক্টর প্রসঙ্গ রিফ্রেশ করুন",
    high_freq_timeline: "উচ্চ-ফ্রিকোয়েন্সি ইভেন্ট টাইমলাইন",
    no_anomalies: "কোনো অসামঞ্জস্যপূর্ণ পতাকা নেই।",
    language: "ভাষা",
    rider_app: "রাইডার অ্যাপ",
    opt_engine_desc: "কম্বিনেটোরিয়াল ভিআরপি সলভার জব, সিমুলেটেড ডিসপ্যাচ খরচ এবং জ্বালানী সাশ্রয়",
    no_solver_plan: "কোনো সলভার প্ল্যান সক্রিয় নেই",
    solver_plan_desc: "যানবাহনের ক্ষমতা গণনা করতে OR-Tools সলভার চালান।",
    dispatch_desc: "ম্যানুয়াল ডেলিভারি ওভাররাইড সারি এবং এসএলএ ওভাররাইড",
    intake_queue: "ইনটেক সারি",
    active_transit: "সক্রিয় ট্রানজিট সারি",
    manual_overrides: "ম্যানুয়াল ডিসপ্যাচ ওভাররাইড",
    live_ops_desc: "অবিরত রাইডার ট্র্যাকিং, গতি ভেক্টর এবং রুট বিচ্যুতি বিশ্লেষণ",
    active_fleet: "সক্রিয় ফ্লিট টেলিমেট্রি"
  }
};

interface SettingsState {
  selectedCity: CityKey;
  selectedLanguage: LanguageKey;
  solverTimeLimit: number;
  workloadBalanceFactor: number;
  priorityWeight: number;
  routingProfile: RoutingProfileKey;
  setCity: (city: CityKey) => void;
  setLanguage: (lang: LanguageKey) => void;
  setSolverTimeLimit: (limit: number) => void;
  setWorkloadBalanceFactor: (factor: number) => void;
  setPriorityWeight: (weight: number) => void;
  setRoutingProfile: (profile: RoutingProfileKey) => void;
  t: (key: string) => string;
}

export const useSettingsStore = create<SettingsState>((set, get) => ({
  selectedCity: "chennai",
  selectedLanguage: "en",
  solverTimeLimit: 3.0,
  workloadBalanceFactor: 0.8,
  priorityWeight: 1.4,
  routingProfile: "bike",
  setCity: (city) => set({ selectedCity: city }),
  setLanguage: (lang) => set({ selectedLanguage: lang }),
  setSolverTimeLimit: (limit) => set({ solverTimeLimit: limit }),
  setWorkloadBalanceFactor: (factor) => set({ workloadBalanceFactor: factor }),
  setPriorityWeight: (weight) => set({ priorityWeight: weight }),
  setRoutingProfile: (profile) => set({ routingProfile: profile }),
  t: (key) => {
    const lang = get().selectedLanguage;
    return translations[lang][key] ?? translations["en"][key] ?? key;
  }
}));
